site_name: Spring
site_author: Chrysan

nav:
  - Home: 'index.md'
  - Self learn:
    - 挖坑: 'Self learn/挖点坑.md'
    - SpringBoot: 'Self learn/Spring Boot.md'
  - Courses:
    - second2th:
      - ads: 
        - week1: 'Courses/second2th/ads/ads week1.md'
      - 数据库系统:
        - week2: 'Courses/second2th/dbs/dbs week2.md'
  - 烤盐:
    - 数一:
      - 微积分:
        - 1 函数&极限&连续: '烤盐/数一/微积分/1 函数&极限&连续.md'
      - 线性代数: '烤盐/数一/线性代数/线性代数.md'
      - 概统: '烤盐/数一/概统/概统.md'

theme: 
  name: material
  theme:
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  language: zh
  # primary: green
  # accent: teal
  palette:
    # - primary: green
    # - accent: teal
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode
    #   primary: green
    #   accent: teal
    
    - media: "prefers-color-scheme: dark"
      scheme: slate
      toggle: 
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: cyan

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green
      accent: teal

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.indexes



markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

# plugins:
#   - search:
#     lang:en
#     foo:bar

extra_css:
  - css/base.css
  